### ISSUE TITLE
Safely fail `variables.find`

### ISSUE THREAD

**Issue by jacobsfletch** [payloadcms/plugin-form-builder#44]
```
0|prod     | Error while sending one or more emails in form submission id: undefined.
0|prod     | TypeError: variables.find is not a function
0|prod     |     at /home/payload/prod/node_modules/@payloadcms/plugin-form-builder/dist/utilities/replaceDoubleCurlys.js:8:43
0|prod     |     at String.replace (<anonymous>)
0|prod     |     at replaceDoubleCurlys (/home/payload/prod/node_modules/@payloadcms/plugin-form-builder/dist/utilities/replaceDoubleCurlys.js:7:20)
0|prod     |     at /home/payload/prod/node_modules/@payloadcms/plugin-form-builder/dist/collections/FormSubmissions/hooks/sendEmail.js:91:81
0|prod     |     at Array.map (<anonymous>)
0|prod     |     at /home/payload/prod/node_modules/@payloadcms/plugin-form-builder/dist/collections/FormSubmissions/hooks/sendEmail.js:85:42
0|prod     |     at step (/home/payload/prod/node_modules/@payloadcms/plugin-form-builder/dist/collections/FormSubmissions/hooks/sendEmail.js:44:23)
0|prod     |     at Object.next (/home/payload/prod/node_modules/@payloadcms/plugin-form-builder/dist/collections/FormSubmissions/hooks/sendEmail.js:25:53)
0|prod     |     at fulfilled (/home/payload/prod/node_modules/@payloadcms/plugin-form-builder/dist/collections/FormSubmissions/hooks/sendEmail.js:16:58)
0|prod     |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by jacobsfletch** [comment]
This plugin is now being maintained in the [Packages Directory](https://github.com/payloadcms/payload/tree/main/packages/plugin-form-builder) of the [Payload Monorepo](https://github.com/payloadcms/payload). This repo will soon be archived and all open issues including this one will be closed. This issue has already been added to [this open discussion](https://github.com/payloadcms/payload/discussions/4466), though, so that it will not get lost. Please refer to that discussion for more details and to continue the conversation.
